name: Build Docker image and push it to GHCR

on:
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/build-image.yaml
      - Containerfile
      - app.py
      - requirements.txt
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME_UPPER: ${{ github.repository }}
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lowercase name
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME_UPPER@L}" >> "${GITHUB_ENV}"

      - name: Retrieve desired release version
        run: |
          git config --global --add safe.directory '*'
          git describe --exact-match --tags HEAD > /dev/null 2>&1 && \
          echo "app_version_oci=$(git describe --exact-match --tags HEAD)" >> "$GITHUB_ENV" || \
          echo "app_version_oci=0.0.0-test_$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.4.0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=sha,format=long

      - name: Build and Push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          push: true
          sbom: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.app_version_oci }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ${{ steps.docker_meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
